import { writeFileSync } from "node:fs";
import { createSeedData } from "../src/services/seed.ts";

const data = createSeedData();
const tables = [
  "business_areas",
  "management_areas",
  "properties",
  "people",
  "project_statuses",
  "project_types",
  "project_levels",
  "projects",
  "project_people",
  "allocations",
  "project_level_links",
];
const sqlValue = (value) =>
  value === null
    ? "null"
    : typeof value === "string"
      ? `'${value.replaceAll("'", "''")}'`
      : String(value);
let sql =
  "-- Fictional Puls test data. Generated by scripts/generate-seed.mjs.\n-- Existing records are preserved on rerun. Test project only.\nbegin;\n";
for (const table of tables) {
  const rows = data[table];
  sql += `insert into public.${table} (${Object.keys(rows[0]).join(",")}) values\n`;
  sql += rows
    .map((row) => `(${Object.values(row).map(sqlValue).join(",")})`)
    .join(",\n");
  sql += "\non conflict do nothing;\n\n";
}
sql += "commit;\n";
writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
